apm install atom-alignment
apm install atom-monokai
apm install atom-monokai-dark
apm install atom-monokai-soda
apm install bliss-monokai-syntax
apm install bliss-monokai-ui
apm install flatten-json
apm install git-plus
apm install json-colorer
apm install ker0x-syntax
apm install language-ansible
apm install language-puppet
apm install language-rpm-spec
apm install language-salt
apm install linter
apm install linter-erb
apm install linter-gcc
apm install linter-perl-check-syntax
apm install linter-puppet
apm install monokai
apm install monokai-plus
apm install monokai-seti
apm install monokai-shade
apm install monokai-slate
apm install pretty-json
apm install python-indent
apm install seti-syntax
apm install seti-ui-beta
apm install shadow
apm install valign

